[package]
name = "examples"
edition = "2021"
publish = false

[dev-dependencies]
once_cell = "1.20.1"
serde_json = "1.0.133"
vate = { path = "../vate", features = ["full"] }

[[example]]
name = "read_me"
path = "read_me.rs"

[[example]]
name = "register"
path = "register.rs"